### PR TITLE
Changed detail icon from icon to label "Details", refs #324

### PR DESCRIPTION
**Pull request by TKosch**
#324

### CODE REVIEW

**Comment by Nik101010** [comment]
@TKosch your change does not fix the issue - the link should be moved from an icon / text in the last column to the entity title, the name of the CsarFile, like it's done with all other entities... the title links to the detail view

**Comment by TKosch** [comment]
@Nik101010 ah ok, so I misunderstood the problem. Fix will be coming soon.

**Comment by przytads** [comment]
I think, the first is the better solution.

**Comment by Nik101010** [comment]
+1 for the first solution

**Pull request merged**
